app:
  name: "web_app"
  mode: "dev"
  port: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backup: 7


mysql:
  host: "127.0.0.1"
  port: 13006
  user: "root"
  password: "sql_demo"

redis:
  host:"127.0.0.1"
  port: 16379
  db: 0

